<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Append' => '',
    'Application' => '',
    'Are you sure to delete this item?' => '',
    'Assigned' => '',
    'Assignments' => '',
    'Avaliable' => '',
    'Class Name' => '',
    'Create' => '',
    'Create Menu' => '',
    'Create Permission' => '',
    'Create Role' => '',
    'Create Route' => '',
    'Create Rule' => '',
    'Create route' => '',
    'Data' => '',
    'Delete' => '',
    'Description' => '',
    'Generate Routes' => '',
    'Help' => '',
    'ID' => '',
    'Menus' => '',
    'Name' => '',
    'Order' => '',
    'Parent' => '',
    'Parent Name' => '',
    'Permission' => '',
    'Permissions' => '',
    'Reset' => '',
    'Roles' => '',
    'Route' => '',
    'Routes' => '',
    'Rule Name' => '',
    'Rules' => '',
    'Search' => '',
    'Type' => '',
    'Update' => '',
    'Update Menu' => '',
    'Update Permission' => '',
    'Update Role' => '',
    'Update Rule' => '',
    'User' => '',
    'Username' => '',
    'Users' => '',
];
